name: gabozago
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  dio: ^5.4.2+1
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.22+1
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  google_sign_in: ^6.2.1
  json_annotation: ^4.8.1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  sign_in_with_apple: ^6.0.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logo/
    - assets/noti/
    - assets/term/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
